services:
  app:
    container_name: body_app
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
      - "8080:8080"
    environment:
      REVERB_SERVER_HOST: 0.0.0.0
      REVERB_SERVER_PORT: 8080
  #   command: ["php", "artisan", "reverb:start", "--debug"]
  nginx:
    container_name: body_nginx
    image: nginx:1.27.2
    restart: no
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/public
      # - ./storage/app:/var/www/storage/app
      - ./docker-configs/nginx/default.conf:/etc/nginx/conf.d/default.conf